### PR TITLE
implement pagination and filtering

### PR DESCRIPTION
**Pull request by tobisanya**

### CODE REVIEW

**Comment by oliversauter** [comment]
Wohooo! we are getting closer and closer! Thanks Tobi!

@hoshomoh @vpolisky @arpitgogia  
Can you review tobi's PR please?

**Comment by hoshomoh** [comment]
@arpitgogia I suggest you use PyCharm as some of the checks above failed because of Indenting and some PEP coding standard.

**Comment by tobisanya** [comment]
@hoshomoh i already did. It's due to the ES version...

**Comment by oliversauter** [comment]
as just discussed, the api has to provide an endpoint to filter for the sources that are chosen for the filter as described in https://github.com/WorldBrain/START-HERE/wiki/Specifications-for-Search-Engine-Prototype#2-the-results-page

**Pull request closed without merging**
