### PR TITLE
Create Postgres Docker image

### PR DESCRIPTION
**Pull request by amitkumarj441**
Added postgresql 9.4! #24 #6

### CODE REVIEW

**Comment by dvigneshwer** [comment]
@amitkumarj441 if this docker file is for building the cortex backend, then I don't see any COPY or git clone commands in the docker file. This docker file basically builds postgres db with ubuntu.

But I feel the objective here is to have a docker file and docker image hosted in the docker hub for people to easily setup their dev environments.

**Comment by oliversauter** [comment]
@dvigneshwer 
> But I feel the objective here is to have a docker file and docker image hosted in the docker hub for people to easily setup their dev environments.

Yes. and for easy deployment.

It seems that we have to rename the issue to: "Create postgres docker image"?

**Comment by amitkumarj441** [comment]
@dvigneshwer You're right! :+1:  I agree with your above statements, but our codebase is on git, so better if we push necessary docker image on hub and then pull it from there for future use.

**Comment by dvigneshwer** [comment]
@amitkumarj441 once you create the docker image, it will be the exact replica of our dev env and while creating the docker image we will either Copy from the host building machine or use the git clone command.

I will create a docker file with few dependencies and i will share few task for you (if you are up for it), let me know.

@oliversauter I feel the issue should be renamed to docker file for cortex.

**Comment by oliversauter** [comment]
@dvigneshwer 
> @oliversauter I feel the issue should be renamed to docker file for cortex.

But isnt it just the postgres file?

**Comment by dvigneshwer** [comment]
@oliversauter yeah we don't require a postgres with ubuntu, we will edit the existing docker file or create a new one for cortex.

**Comment by oliversauter** [comment]
what do you mean we dont require postgres with ubuntu?

**Comment by dvigneshwer** [comment]
@oliversauter Cortex has more dependencies like the django framework, postgres configurations etc we need to include those too in the docker file, so we don't require the docker file which only has postgres in it.

**Comment by oliversauter** [comment]
ah ok, so its for the sake of simplicity to include the postgres into the main file. I see.

**Comment by amitkumarj441** [comment]
@dvigneshwer I have my exams from Monday and I'll be able to handle tasks after a week. If you want, then you can share me the tasks.

**Comment by dvigneshwer** [comment]
Cool @amitkumarj441 I will create the docker file and push the image, you can always test it and get back with constructive feedbacks.

Best of luck with exams :)

**Comment by amitkumarj441** [comment]
Thanks @dvigneshwer for your prompt response! Yes, I'll test your created images :+1:

**Comment by oliversauter** [comment]
@amitkumarj441 Best of luck from me as well!

@dvigneshwer yeah i think its a good idea if we just go forward with that and @amitkumarj441 you may be able to make a PR review and give feedback. We need to get the stuff on production, so we can let the crawler start indexing websites.

**Comment by amitkumarj441** [comment]
Yes @oliversauter ! As of now, I'm able to review for docker, Elasticsearch, AWS, Kibana, CAdvisor.

**Comment by dvigneshwer** [comment]
@oliversauter on it, I think we will have a docker image by Monday in the docker hub.

**Comment by oliversauter** [comment]
nice you 2! looking forward to it :)

**Pull request merged**
