### PR TITLE
implement pagination and filtering on the search api

### PR DESCRIPTION
**Pull request by tobisanya**
blocks finishing of #21

### CODE REVIEW

**Comment by oliversauter** [comment]
Do I understand this correctly, this now fully implements the stuff we talked about yesterday with filtering for domains?

**Comment by tobisanya** [comment]
@oliversauter yeah it does what we discussed yesterday...and it does it in a way that can be extended to other fields (instead of domains only)

**Comment by oliversauter** [comment]
great! What is the purpose of the delay?

**Comment by tobisanya** [comment]
Its just for tests, doesn't affect the main application
It tries to simulate the initial reindexing of the database to elastic search, and tries to assert that what was indexed can be searched

**Comment by oliversauter** [comment]
understood.

**Comment by hoshomoh** [comment]
@tobisanya good job. @arpitgogia kindly take a look at this so we can merge. It seems good to me.

**Comment by arpitgogia** [comment]
Looks good to me too. A small question, which part of the code shows pagination?

**Comment by oliversauter** [comment]
blocks finishing of #21

**Comment by oliversauter** [comment]
@tobisanya great! :) looking forward seeing it in action. Can you answer arpits question quickly? It is also interesting for me to understand the code:)

**Comment by tobisanya** [comment]
@arpitgogia @oliversauter  elasticsearch handles pagination beautifully

> Pagination of results can be done by using the from and size parameters. The from parameter defines the offset from the first result you want to fetch. The size parameter allows you to configure the maximum amount of hits to be returned.

Line 88 and 89 of  `worldbrain/cortex/search/indexes.py`:
~~~~
body['size'] = self.SIZE
body['from'] = self.OFFSET
~~~~

**Pull request merged**
