### PR TITLE
#41

### PR DESCRIPTION
**Pull request by hoshomoh**
Removed html column from table ```articles``` and be added to ```all_urls```

### CODE REVIEW

**Comment by oliversauter** [comment]
why is in the articles dictionary only the title as a field available?
Shouldn't there be more?

```
article_dict = {
        'url': 'url',
        'domain_name': 'domain_name',
        'title': 'very_unique_title',
        'publish_date': '2016-07-25',
        'parse_time': 'parse_time',
        'state': 'parsed',
    }
```

**Comment by hoshomoh** [comment]
@tobisanya Implemented that. And that is just a sample article for testing purpose. Adding the remaining fields is really not important as it would not make any significant change to the coverage

**Comment by hoshomoh** [comment]
@WorldBrain/core-team-cortex I am just going to merge this as it's really not a big change. But, feel free to ask questions and drop comments.

**Comment by oliversauter** [comment]
ok, then I need a little bit more context to understand the setup. 

Where can I see the whole article dictionary to check if every necessary field is there like described in: https://github.com/WorldBrain/START-HERE/wiki/Database-Architecture:-Table-Structures#articles

**Comment by hoshomoh** [comment]
From line 89 **https://github.com/WorldBrain/cortex/blob/master/worldbrain/cortex/models.py** if that helps

**Comment by hoshomoh** [comment]
@oliversauter @tobisanya @arpitgogia feel free to check this and drop your comment if you have any review. Merging now.

**Comment by oliversauter** [comment]
i thought there is a problem with #45 if we merge this before it?

**Comment by hoshomoh** [comment]
The problem is that ```html``` column is no longer in ```articles``` table, but @arpitgogia PR is still trying to add stuff to that column. This PR definitely needs to go in, but its a good thing we caught that before its approved. So, all we have to do is update that PR.

**Comment by oliversauter** [comment]
understood

**Comment by arpitgogia** [comment]
If I remember correctly I mentioned that mine should be merged after the PR for #41 as it was dependent. I'm already using html from ```all_urls```

**Comment by arpitgogia** [comment]
Oh I found the mistake. The ```html``` attribute doesn't need to be added to ```articles``` anymore right?

**Comment by oliversauter** [comment]
how is it, do you get notifications when people react to your posts?

**Comment by hoshomoh** [comment]
@oliversauter  if that question is for me. Yes I get GitHub notification. And now that we have slack integrated. It's even more  awesome than ever.

**Comment by arpitgogia** [comment]
No Not for reactions like thumbs up etc. I keep tabs open on my browser for active issues and circle around after some time :smile:

**Comment by oliversauter** [comment]
it was actually for arpit, as we both gave him the 👍 on his post. And yes, i find it also super super super awesome to get the github notifications in slack :)

**Comment by oliversauter** [comment]
great idea! @arpitgogia

**Pull request merged**
