### PR TITLE
Adjust models: Source, AllUrls; Add migrate script

### PR DESCRIPTION
**Pull request by vpolisky**
**# I. Model adjustments:**

- Adjusted _Source_ and _AllUrls_ models correspondent to [https://github.com/WorldBrain/cortex/issues/46](https://github.com/WorldBrain/cortex/issues/46)
- Adjusted _SourceAdmin_
- Adjusted _SourceStates_ and _AllUrlsStates_ correspondent to [https://github.com/WorldBrain/cortex/issues/46](https://github.com/WorldBrain/cortex/issues/46)
- Added a bash script (_worldbrain/migrate.sh_) to make migrations faster

**# II. Spider module:**

Goal
-
Exctracting *URL*s and their *html* contents for domains in the *Source* 
table and saving them into the *AllUrl* table

Input
-
Domain names from the *Source* table which are not processed by spider yet and
are ready for crawling

Output
-
Saves extracted *URL*s into the *AllUrl* table with:

- `source = Initial source domain`
- `url = URL`
- `html = HTML content for the URL`
- `is_article = False`
- `state = AllUrlStates.PENDING`
 
Updates the correspondent Source fields:

- `state = SourceStates.CRAWLED` if succeeded
- `state = SourceStates.FAILED` if failed
- `last_time_crawled = timestamp of successfull crawling` if succeeded
- `last_error_message = error message` if failed

Technical implementation
-

- Django management command within the __cortex__ app (*/cortex/management/commands/feedspider.py*):

    Run command: `python manage.py feedspider` [should be started 
    periodically as a cronjob]
    
    The command looks for sources which are not processed by spider and ready for crawling 
    and pushes their domain names into the __RabbitMQ__ message queue.
    
- __RabbitMQ__ message queue (currently running on my private server on *polisky.me*):

    *__vhost__: /worldbrain,__user__: worldbrain, __password__: worldbrain, __queue__: worldbarin*
    
    Domain names are queued in the queue and delivered to consumer as soon as available.
    
- A consumer daemon waiting for domain names in the queue (*/cortex/daemons/spider.py*):

    Run command: `./start_spider.sh` from within the *worldbrain/* directory
    
    The daemon is waiting for domain names in the message queue and 
    asynchronously starting crawler processes for each incoming domain name. 
    After crawling, the database is updated.
    
Further suggestions:
-

- Run *RabbitMQ* server on a dedicated server
- Start *spider* via *uWSGI*
- Make spider feeder a daemon process and trigger its handler on *Source*'s 
ready state transition via *HTTP*

### CODE REVIEW

**Comment by hoshomoh** [comment]
Good job @vpolisky

**Comment by oliversauter** [comment]
sweet! This now means the crawler works and is connected to the admin interface? What is missing so we could start indexing the first domains?

**Comment by vpolisky** [comment]
@oliversauter I'm working on tests for the spider right now and will make a PR today or tomorrow with finished spider, as soon as the tests are finished. This PR did not include the spider module, since I needed these adjustments in the models etc first. But the crawler works now. I tested it manually.
@hoshomoh Thanks for your advices!

**Comment by oliversauter** [comment]
Great!

@hoshomoh @e911miri 
**2 things:**
 1. Can you get the back-end admin interface and the crawler running on AWS so we can start indexing before we have the client finished? Would be great ASAP.
 2. What do you think we will have in server costs by letting those crawlers run with AWS (practically all day)? 
3. We also still have the 100€ a month for redhat's open shift and all the perks from [here](https://hyp.is/9ATMTIKSEeakhlvxNlUYYg/fi.co/partners) "Section: Premier Partner Ressources"

**Comment by oliversauter** [comment]
> state = SourceStates.READY if succeeded

isn't the state READY given when a source has been marked as ready for crawling?
at least it was talked about this [here](https://github.com/WorldBrain/cortex/issues/40#issuecomment-247254905) with @hoshomoh

**Comment by vpolisky** [comment]
@oliversauter Oh, sorry, it was my error while writing the comment. Of course, the state is set to CRAWLED

**Comment by oliversauter** [comment]
Ah ok:)

Is there a limit of sources that can be crawled at the same time?

So now that the spider is there, is there anything missing in order to put it up to production and then start indexing stuff?

**Comment by vpolisky** [comment]
@oliversauter 

> Is there a limit of sources that can be crawled at the same time?

Surely, there are ;) We should experiment and figure out what are the bottlenecks. At the moment, I think, that writing into the database could be the most important one. I tested the chain in a simpler setup with in-memory MongoDB optimized for write operations and without long-running processes. Then, the CPU usage was very high at 500 ops/sec. At the same time, the CPU usage of the RabbitMQ server was about 1,5%. So, I think, message delivery shouldn't be a problem, but writing into the database.

**Comment by oliversauter** [comment]
> So, I think, message delivery shouldn't be a problem, but writing into the database.

What is the expected problem?

**Comment by vpolisky** [comment]
> What is the expected problem?

If writes into the database are not fast enough, the delivery rate (RabbitMQ -> consumer) will decrease. This will imply that probably the queue will increase (ideally, it should be empty). The performance of RabbitMQ will then significantly decrease such that the queue will fill up. Starting multiple spider processes wouldn't be a solution in that case, since they would be blocked by the database and unable to consume the messages faster.

However, this scenario is, from my sight, not realistic at the beginning, because it can happen only at high write rates. In particular, if we feed the spider only periodically, this shouldn't be an issue.

BTW do we have documentation about the database organization like replica set etc?

**Comment by oliversauter** [comment]
ok understood, yeah that will be a thing of the scalability then. 

> BTW do we have documentation about the database organization like replica set etc?
you mean backups?

**Comment by vpolisky** [comment]
> you mean backups?

I mean replica set like: a primary server optimized for writes and replicating secondaries for reads etc

**Comment by oliversauter** [comment]
No, I dont think so.

**Comment by oliversauter** [comment]
As soon as we have the prototype running we are going to focus our work on 3 things:

1. Optimising Search
2. Scalability/Stability of System (Crawler, DB)
3. MVP Feature Planning

**Comment by oliversauter** [comment]
can we close this? @hoshomoh @tobisanya 

@amitkumarj441, since you have knowledge about scrapy, it would be great if you can check on this PR!

**Comment by hoshomoh** [comment]
@oliversauter no we can't. @vpolisky please can we make sure all the test pass so we can merge this.

**Comment by oliversauter** [comment]
@hoshomoh ah ok. yeah vitaly mentioned that he wants to finish up the tests this week. Thought they might come with another PR.

**Comment by amitkumarj441** [comment]
@oliversauter Yes, I'll soon initiate a PR for the same. Please don't close this issue!

**Comment by hoshomoh** [comment]
@oliversauter I think we should clarify from him. He might want to update this PR and not make a new one.

**Comment by oliversauter** [comment]
@amitkumarj441 What do you mean you want to do it for the same?

@hoshomoh I think it was a misunderstanding from my side. Actually it is now clear to me, that @vitaly just updates the PR as soon as he has the tests ready.

**Comment by amitkumarj441** [comment]
@oliversauter First of all, let me fix this PR to pass all test cases and then I'll add more for optimising search!

**Comment by oliversauter** [comment]
@amitkumarj441
>First of all, let me fix this PR to pass all test cases 

please sync this effort with vitaly, since he is already working on it. 

> add more for optimising search!

If you plan to implement search optimisation, please wait until we gathered all the possible improvements and then discussed them. 
You may want to split up your suggestions in issue #58 beforehand so that they become clearer (at least to me) :) (https://github.com/WorldBrain/cortex/issues/58#issuecomment-249418221)
+ adding some new ones.

**Comment by vpolisky** [comment]
@oliversauter @hoshomoh @amitkumarj441 I'll update the PR today at the evening.
One question. In my fork, I - additionally to the management command - implemented, that the spider is fed with domain name automatically when the source state is being updated to ready (= on Source.ready call). Is this a good idea? Should I add this to the PR?

**Comment by oliversauter** [comment]
@vpolisky why should it be a bad idea? As far as I understood, the state "Ready" is only given when a person marks the source via the backend admin interface. This implies that it has been manually checked and is ready to go. 

This is correct, @hoshomoh ?

**Comment by hoshomoh** [comment]
@oliversauter @vpolisky I think it's a good idea that you add it to your PR. Good job

**Comment by amitkumarj441** [comment]
@oliversauter I'm still trying to re-edit this PR but I don't have push access to the spider. Please provide me the access to spider!

**Comment by vpolisky** [comment]
@oliversauter @hoshomoh The question about the automated invocation of the spider arised  because of these two points:
1) At the moment, source states are switched manually, right? But if later we will have an automation of this step, could it happen that new domains will be pushed into the message queue on too fast rate such that the consumer is not able to consume the messages so fast?
2) Spider invocation is triggered in my code by the Source.ready method. Does it really guarantee that it will always happen, when the state is switched, or are there also state transitions which are not triggered by Source.ready?

**Comment by oliversauter** [comment]
>1) At the moment, source states are switched manually, right? But if later we will have an automation of this step, could it happen that new domains will be pushed into the message queue on too fast rate such that the consumer is not able to consume the messages so fast?

It will run for quite some time manually, so my suggestion is to neglect this for now. 

> 2) Spider invocation is triggered in my code by the Source.ready method. Does it really guarantee that it will always happen, when the state is switched, or are there also state transitions which are not triggered by Source.ready?

What could prevent the state from being switched?

**Comment by vpolisky** [comment]
> What could prevent the state from being switched?

What I mean is rather, that we should guarantee, that the source state can only be switched via e.g. `source.ready()` instead of `source.state = SourceStates.READY.value`. In the latter case, the spider won't be triggered.

**Comment by oliversauter** [comment]
If you think it is a better option, then go ahead. Does this have impact on other people's work? 

If yes, what needs to be changed in which parts?

**Comment by vpolisky** [comment]
> Does this have impact on other people's work?

This has impact in that sense, that the only way of state transitions should be only via the transition methods. I'll try to figure out whether it's possible to guarantee that programmatically. That would be a good solution from my sight. Otherwise, developers should take into account that fact when writing code.

> If yes, what needs to be changed in which parts?

Actually, I assume that only a small piece of code is affected, namely those, where the pending state is being set to ready.

However, we still do have the management command to ensure that all ready sources are crawled in the case that some source's state happens to be set to ready without calling its ready-method.

**Pull request merged**
