### PR TITLE
crawler/model README

### PR DESCRIPTION
**Pull request by lwm**
** DO NOT MERGE **

Please let me know what you think!

Anything goes. We need this part of the system to be rock solid if we want to actually get any decent content from the web.

View the `README.md` in markdown [here](https://github.com/lwm/cortex/blob/d094a47640239098eb6dde02736c32a53cf4221b/readmes/DB-MODEL.md).

### CODE REVIEW

**Comment by oliversauter** [comment]
As a starter, I would suggest we first manually skim the urls for patterns like for example URLS that have "/category/" or “/tags/" in them. Then we can also look for the length of the body text to see if it is actually an article.

i guess we wont get around first looking over our data manually.

And in the MVP fashion we first should look how to have a workflow that gets us content, before filtering it.

**Comment by oliversauter** [comment]
As a recap of the phonecall/chat with @lwm 

Automation of filtering out "non-articles" is still premature to talk about. 
In order to automate the filtering and automatic detection of "non-articles" we first have to do it manually.
Priority now is to get the pipeline of crawling working.

The whole process (Linkchecker - linkcleaner - HTML crawling - Entitity (title, body etc.) parsing)  we need to build is described here: https://github.com/WorldBrain/cortex/issues/1#issuecomment-230465195
I updated it according to where the misunderstandings were before. 

The output of all steps should be saved in order for us to manually look over how to automate the filtering between the different steps.

Anything to add, i missed? (@lwm)

**Comment by lwm** [comment]
Nope, I think that is it.

> Automation of filtering out "non-articles" is still premature to talk about. 

The sooner we start, the better. We will still focus on the MVP, but if anyone interested in the ML aspect of this project is interested, please go for it!

> Priority now is to get the pipeline of crawling working.

It's coming :)

I will leave this PR open as I experiment with the model and update accordingly.

**Comment by lwm** [comment]
Closing due to messing with master branch.

In any case, I think my model is insufficient because storing URL relation in a database is more like a tree structure ... 

Anyway, frontera seems to be the way to go here (I think it has a model for this).

https://github.com/scrapinghub/frontera

Investigating ...

**Pull request closed without merging**
