### PR TITLE
#31

### PR DESCRIPTION
**Pull request by hoshomoh**
Fix for #18 
Implemented #33, #32, #31

### CODE REVIEW

**Comment by hoshomoh** [comment]
@WorldBrain/core-team-cortex Please review so we can merge

**Comment by oliversauter** [comment]
@arpitgogia @tobisanya this is the PR, which needs review. 

Thanks guys!

**Comment by tobisanya** [comment]
looks good to me

**Comment by arpitgogia** [comment]
Looks fine!

**Pull request merged**
